### ISSUE TITLE
Response.json() get error

### ISSUE THREAD

**Issue by sukalyanM** [Wintellect/DataScienceExamples#1] opened 2018-09-05 09:54 UTC
Hi,
I m using your code of Simple regression Persistence notebook with example which you mention.
Find error as

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-256-c7aac04ca6f3> in <module>()
      1 
----> 2 Response.json()

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    894                     # used.
    895                     pass
--> 896         return complexjson.loads(self.text, **kwargs)
    897 
    898     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

please help
I had also tried request.get(url).json() also,but same error is there.

**Comment by jwood803** [comment] 2018-09-05 10:19
Hi! Sorry you've having this issue. Do you have the Flask code from the `SimpleLinearRegressionAPI.py` file running as well? If you do, double check the `BASE_URL` string is the same as what Flask gives you.

Hope that helps, but definitely let me know if you're still having issues. 😄

**Comment by sukalyanM** [comment] 2018-09-05 10:35
I had use SimpleLinearRegressionAPI.py also,its give url "http://127.0.0.1:5000/"
I had tried it as BASE_URL in my notebook,getting same error

**Comment by jwood803** [comment] 2018-09-05 11:06
I think the issue is that the `SimpleLinearRegressionAPI.py` and the persistence notebook need to be run in the same directory. The reason is that the notebook dumps the model file in the same directory the notebook is in and the API script reads from the same directory that it is in.

Try to move the persisted model file to the same folder where the API is running and see if that fixes it.

**Comment by sukalyanM** [comment] 2018-09-05 12:00
I had SimpleLinearRegressionAPI.py,Pickle files, as well as persistence notebook all are in same folders.

I had tried out persistance notebook code after copying SimpleLinearRegressionAPI.py on same folders where all pickle dumps and notebook is present.
Still facing same issue in Response.Json()
Please help

**Comment by jwood803** [comment] 2018-09-05 12:05
Does the Flask output have any more information as to what the error may be?

**Comment by sukalyanM** [comment] 2018-09-05 12:56
First Screenshoot from command prompt.
(base) C:\Users\A6415>python SimpleLinearRegressionAPI.py
 * Serving Flask app "SimpleLinearRegressionAPI" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 268-926-862
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Second screenshot from persistence notebook.
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-79-5eab712458d3> in <module>()
----> 1 Response.json()

C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in json(self, **kwargs)
    894                     # used.
    895                     pass
--> 896         return complexjson.loads(self.text, **kwargs)
    897 
    898     @property

C:\ProgramData\Anaconda3\lib\json\__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    317             parse_int is None and parse_float is None and
    318             parse_constant is None and object_pairs_hook is None and not kw):
--> 319         return _default_decoder.decode(s)
    320     if cls is None:
    321         cls = JSONDecoder

C:\ProgramData\Anaconda3\lib\json\decoder.py in decode(self, s, _w)
    337 
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    340         end = _w(s, end).end()
    341         if end != len(s):

C:\ProgramData\Anaconda3\lib\json\decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jwood803** [comment] 2018-09-05 14:35
Is there anything in the Flask output when you run the cell in Jupyter that produces the `response.json()` error?

**Comment by sukalyanM** [comment] 2018-09-06 04:32
Solved..Thanks a lot.
I m developing NLP based api and try to call output in notebook,your guidance help a lot.
if,I face any issue i will seek your help.

**Comment by jwood803** [comment] 2018-09-06 09:56
Awesome! Glad you got it working. I'll close the issue, but if feel free to open it back up if it comes up again. I'll be glad to help! 😄

**Closed as completed by jwood803** 2018-09-06 09:56 UTC
